Added caching for Request results from database queries using javax.cache (JSR 107)
BBMRI-ERIC/negotiator-v2 pull request #141
Opened 2022-09-30 10:06 UTC by konradlang

Added caching for Request results from database queries using javax.cache (JSR 107):

Added Spring Framework to support caching;
Added ehcache as cache provider;

2022-09-30 10:16 UTC, RadovanTomik commented on pom.xml
> -        <database.server>localhost</database.server>
please return it to localhost

2022-09-30 10:18 UTC, RadovanTomik requested changes
👍

2022-09-30 10:24 UTC, konradlang commented on pom.xml
> -        <database.server>localhost</database.server>
done.

2022-09-30 11:02 UTC, RadovanTomik approved these changes
👍

2022-10-18 07:45 UTC, konradlang commented
Marginal performance improvement, not merged.

2022-10-18 07:45 UTC, closed without merging